[tox]
envlist = py312

[testenv:users_unit]
description = run unit test for dailymotion users
passenv = *
allowlist_externals = poetry,date
skip_install = true
commands =
    date  # show the datetime ensure that the time is the same as the CI VM with the external services
    poetry install -v --with test
    poetry show --tree
    poetry run pytest -svv \
        app/tests/unit/create_user_use_case_test.py \
        app/tests/unit/enable_user_account_use_case_test.py

[testenv:users_integration]
description = run postgres integration test for dailymotion users
passenv = *
allowlist_externals = poetry,date
skip_install = true
commands =
    date  # show the datetime ensure that the time is the same as the CI VM with the external services
    poetry install -v --with test
    poetry show --tree
    poetry run pytest -svv \
        app/tests/integration/repositories/postgresdb_repository_test.py \
        app/tests/integration/repositories/redis_repository_test.py \
        app/tests/integration/drivers/create_user_test.py \
        app/tests/integration/drivers/enable_user_account_test.py
